// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrcu2x0dhdxGfYPR7p3FxSiWlIWTkjdhE',
    appId: '1:557866127065:web:d2a2eec6ad327dcef0f8c8',
    messagingSenderId: '557866127065',
    projectId: 'volunteer-impact',
    authDomain: 'volunteer-impact.firebaseapp.com',
    databaseURL: 'https://volunteer-impact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volunteer-impact.firebasestorage.app',
    measurementId: 'G-QEQ7MYWL8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUo7_A-1LzKD3CkHDpSnBKYus3WJIAscg',
    appId: '1:557866127065:android:1808b98553b28f4ef0f8c8',
    messagingSenderId: '557866127065',
    projectId: 'volunteer-impact',
    databaseURL: 'https://volunteer-impact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volunteer-impact.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxWk0jAxiksIz2hqL6Bf6bQN2jXxi0wq8',
    appId: '1:557866127065:ios:11c9562bd9f086ebf0f8c8',
    messagingSenderId: '557866127065',
    projectId: 'volunteer-impact',
    databaseURL: 'https://volunteer-impact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volunteer-impact.firebasestorage.app',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxWk0jAxiksIz2hqL6Bf6bQN2jXxi0wq8',
    appId: '1:557866127065:ios:11c9562bd9f086ebf0f8c8',
    messagingSenderId: '557866127065',
    projectId: 'volunteer-impact',
    databaseURL: 'https://volunteer-impact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volunteer-impact.firebasestorage.app',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrcu2x0dhdxGfYPR7p3FxSiWlIWTkjdhE',
    appId: '1:557866127065:web:69a69c0abd0ff012f0f8c8',
    messagingSenderId: '557866127065',
    projectId: 'volunteer-impact',
    authDomain: 'volunteer-impact.firebaseapp.com',
    databaseURL: 'https://volunteer-impact-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'volunteer-impact.firebasestorage.app',
    measurementId: 'G-JNEWS7ZHYJ',
  );
}
